#!/bin/bash


function cleanUser() {
    USERNAME="$1"
	rm "$ROOMS/$(load user location)/players/$1"
	rm "$USERS/$1/proc"
	rm "$CONNECTED_PLAYERS/$1"
}

function userProcAlive() {
    kill -s 0 "$(cat "$USERS/$1/proc")" 2>/dev/null
}