#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" || exit $?
DATA="$DIR/data"
BIN="$DIR/bin"
USERS="$DATA/users"
SETTINGS="$DATA/settings"
RUNTIME="$DATA/runtime"
ROOMS="$DATA/rooms"
PGID=$(ps -o pgid= $$ | grep -o '[0-9]*') || exit $?

